### ISSUE TITLE
Login y registro

### ISSUE THREAD

**Issue by miguelmoya1** [miguelmoya1/autonomo#3]
Comprobar en el backend login y registro

**Comment by CristianPumaES6** [comment]
Hola Miguel,

Este proyecto en que conciste y que finalidad tiene?

Tengo conocimientos en Angular y NestJS.

Espero tu comentario.

Saludos

**Comment by miguelmoya1** [comment]
Buenas,

Este proyecto era para poder gestionar  todo el tema de autónomo intracomunitario, porque me hice autonomo y así podría gestionar el tema de emitir facturas y guardarlas en una web, pero tuve que abandonar el proyecto porque son demasiados casos para contemplar, aunque si es solo para intracomunitario, va bien
